require_relative PathFor[:textmate_tools]

# 
# C++ specific tokens
# 
    # TODO: 
        # finish the specifiers https://en.cppreference.com/w/cpp/language/declarations 
        # https://en.cppreference.com/w/cpp/language/declarations
        # look at https://en.cppreference.com/w/cpp/language/function to implement better member function syntax

tokens = [
    # operators
    { representation: "::"                   , name: "scope-resolution"               , isOperator: true,                                      isBinaryOperator:  true, presedence:  1   , evaledLeftToRight: true, isInFixOperator:   true },
    { representation: "++"                   , name: "post-increment"                 , isOperator: true, canAppearAfterOperatorKeyword: true, isUrnaryOperator:  true, presedence:  2.1 , evaledLeftToRight: true, isPostFixOperator: true },
    { representation: "--"                   , name: "post-decrement"                 , isOperator: true, canAppearAfterOperatorKeyword: true, isUrnaryOperator:  true, presedence:  2.1 , evaledLeftToRight: true, isPostFixOperator: true },
    { representation: "()"                   , name: "function-call"                  , isOperator: true, canAppearAfterOperatorKeyword: true,                          presedence:  2.3 , evaledLeftToRight: true,                         },
    { representation: "[]"                   , name: "subscript"                      , isOperator: true, canAppearAfterOperatorKeyword: true,                          presedence:  2.4 , evaledLeftToRight: true,                         },
    { representation: "."                    , name: "object-accessor"                , isOperator: true,                                      isBinaryOperator:  true, presedence:  2.5 , evaledLeftToRight: true, isInFixOperator:   true },
    { representation: "->"                   , name: "pointer-accessor"               , isOperator: true, canAppearAfterOperatorKeyword: true, isBinaryOperator:  true, presedence:  2.5 , evaledLeftToRight: true, isInFixOperator:   true },
    { representation: "++"                   , name: "pre-increment"                  , isOperator: true, canAppearAfterOperatorKeyword: true, isUrnaryOperator:  true, presedence:  3.1 , evaledRightToLeft: true, isPreFixOperator:  true },
    { representation: "--"                   , name: "pre-decrement"                  , isOperator: true, canAppearAfterOperatorKeyword: true, isUrnaryOperator:  true, presedence:  3.1 , evaledRightToLeft: true, isPreFixOperator:  true },
    { representation: "+"                    , name: "plus"                           , isOperator: true, canAppearAfterOperatorKeyword: true, isUrnaryOperator:  true, presedence:  3.2 , evaledRightToLeft: true, isPreFixOperator:  true },
    { representation: "-"                    , name: "minus"                          , isOperator: true, canAppearAfterOperatorKeyword: true, isUrnaryOperator:  true, presedence:  3.2 , evaledRightToLeft: true, isPreFixOperator:  true },
    { representation: "!"                    , name: "logic-not"                      , isOperator: true, canAppearAfterOperatorKeyword: true, isUrnaryOperator:  true, presedence:  3.3 , evaledRightToLeft: true, isPreFixOperator:  true , isLogicicalOperator: true },
    { representation: "not"                  , name: "logic-not-word"                 , isOperator: true,                                      isUrnaryOperator:  true, presedence:  3.3 , evaledRightToLeft: true, isPreFixOperator:  true , isLogicicalOperator: true, isOperatorAlias: true },
    { representation: "~"                    , name: "bitwise-not"                    , isOperator: true, canAppearAfterOperatorKeyword: true, isUrnaryOperator:  true, presedence:  3.3 , evaledRightToLeft: true, isPreFixOperator:  true },
    { representation: "compl"                , name: "bitwise-not-word"               , isOperator: true,                                      isUrnaryOperator:  true, presedence:  3.3 , evaledRightToLeft: true, isPreFixOperator:  true , isOperatorAlias: true},
    { representation: "*"                    , name: "dereference"                    , isOperator: true, canAppearAfterOperatorKeyword: true, isUrnaryOperator:  true, presedence:  3.5 , evaledRightToLeft: true, isPreFixOperator:  true },
    { representation: "&"                    , name: "reference"                      , isOperator: true, canAppearAfterOperatorKeyword: true, isUrnaryOperator:  true, presedence:  3.6 , evaledRightToLeft: true, isPreFixOperator:  true },
    { representation: "sizeof"               , name: "sizeof"                         , isOperator: true,                                      isUrnaryOperator:  true, presedence:  3.7 , evaledRightToLeft: true, isPreFixOperator:  true, isFunctionLike: true },
    { representation: "sizeof..."            , name: "variadic-sizeof"                , isOperator: true,                                      isUrnaryOperator:  true, presedence:  3.7 , evaledRightToLeft: true, isPreFixOperator:  true, isFunctionLike: true },
    { representation: "new"                  , name: "new"                            , isOperator: true, canAppearAfterOperatorKeyword: true, isUrnaryOperator:  true, presedence:  3.8 , evaledRightToLeft: true, isPreFixOperator:  true },
    { representation: "new[]"                , name: "new-array"                      , isOperator: true, canAppearAfterOperatorKeyword: true, isUrnaryOperator:  true, presedence:  3.8 , evaledRightToLeft: true, isPreFixOperator:  true },
    { representation: "delete"               , name: "delete"                         , isOperator: true, canAppearAfterOperatorKeyword: true, isUrnaryOperator:  true, presedence:  3.9 , evaledRightToLeft: true, isPreFixOperator:  true },
    { representation: "delete[]"             , name: "delete-array"                   , isOperator: true, canAppearAfterOperatorKeyword: true, isUrnaryOperator:  true, presedence:  3.9 , evaledRightToLeft: true, isPreFixOperator:  true },
    { representation: ".*"                   , name: "object-accessor-dereference"    , isOperator: true,                                      isBinaryOperator:  true, presedence:  4   , evaledLeftToRight: true, isInFixOperator:   true },
    { representation: "->*"                  , name: "pointer-accessor-dereference"   , isOperator: true, canAppearAfterOperatorKeyword: true, isBinaryOperator:  true, presedence:  4   , evaledLeftToRight: true, isInFixOperator:   true },
    { representation: "*"                    , name: "multiplication"                 , isOperator: true, canAppearAfterOperatorKeyword: true, isBinaryOperator:  true, presedence:  5   , evaledLeftToRight: true, isInFixOperator:   true },
    { representation: "/"                    , name: "division"                       , isOperator: true, canAppearAfterOperatorKeyword: true, isBinaryOperator:  true, presedence:  5   , evaledLeftToRight: true, isInFixOperator:   true },
    { representation: "%"                    , name: "modulus"                        , isOperator: true, canAppearAfterOperatorKeyword: true, isBinaryOperator:  true, presedence:  5   , evaledLeftToRight: true, isInFixOperator:   true },
    { representation: "+"                    , name: "addition"                       , isOperator: true, canAppearAfterOperatorKeyword: true, isBinaryOperator:  true, presedence:  6   , evaledLeftToRight: true, isInFixOperator:   true },
    { representation: "-"                    , name: "subtraction"                    , isOperator: true, canAppearAfterOperatorKeyword: true, isBinaryOperator:  true, presedence:  6   , evaledLeftToRight: true, isInFixOperator:   true },
    { representation: "<<="                  , name: "bitwise-shift-left-assignment"  , isOperator: true, canAppearAfterOperatorKeyword: true, isBinaryOperator:  true, presedence: 16.6 , evaledRightToLeft: true, isInFixOperator:   true , isAssignmentOperator: true },
    { representation: ">>="                  , name: "bitwise-shift-right-assignment" , isOperator: true, canAppearAfterOperatorKeyword: true, isBinaryOperator:  true, presedence: 16.6 , evaledRightToLeft: true, isInFixOperator:   true , isAssignmentOperator: true },
    { representation: "<<"                   , name: "bitwise-shift-left"             , isOperator: true, canAppearAfterOperatorKeyword: true, isBinaryOperator:  true, presedence:  7   , evaledLeftToRight: true, isInFixOperator:   true },
    { representation: ">>"                   , name: "bitwise-shift-right"            , isOperator: true, canAppearAfterOperatorKeyword: true, isBinaryOperator:  true, presedence:  7   , evaledLeftToRight: true, isInFixOperator:   true },
    { representation: "<=>"                  , name: "three-way-compare"              , isOperator: true, canAppearAfterOperatorKeyword: true, isBinaryOperator:  true, presedence:  8   , evaledLeftToRight: true, isInFixOperator:   true , isComparisonOperator: true},
    { representation: "<"                    , name: "less-than"                      , isOperator: true, canAppearAfterOperatorKeyword: true, isBinaryOperator:  true, presedence:  9.1 , evaledLeftToRight: true, isInFixOperator:   true , isComparisonOperator: true},
    { representation: "<="                   , name: "less-than-or-equal-to"          , isOperator: true, canAppearAfterOperatorKeyword: true, isBinaryOperator:  true, presedence:  9.1 , evaledLeftToRight: true, isInFixOperator:   true , isComparisonOperator: true},
    { representation: ">"                    , name: "greater-than"                   , isOperator: true, canAppearAfterOperatorKeyword: true, isBinaryOperator:  true, presedence:  9.2 , evaledLeftToRight: true, isInFixOperator:   true , isComparisonOperator: true},
    { representation: ">="                   , name: "greater-than-or-equal-to"       , isOperator: true, canAppearAfterOperatorKeyword: true, isBinaryOperator:  true, presedence:  9.2 , evaledLeftToRight: true, isInFixOperator:   true , isComparisonOperator: true},
    { representation: "=="                   , name: "equal-to"                       , isOperator: true, canAppearAfterOperatorKeyword: true, isBinaryOperator:  true, presedence: 10   , evaledLeftToRight: true, isInFixOperator:   true , isComparisonOperator: true},
    { representation: "!="                   , name: "not-equal-to"                   , isOperator: true, canAppearAfterOperatorKeyword: true, isBinaryOperator:  true, presedence: 10   , evaledLeftToRight: true, isInFixOperator:   true , isComparisonOperator: true},
    { representation: "not_eq"               , name: "not-equal-to-word"              , isOperator: true,                                      isBinaryOperator:  true, presedence: 10   , evaledLeftToRight: true, isInFixOperator:   true , isComparisonOperator: true, isOperatorAlias: true,},
    { representation: "&"                    , name: "bitwise-and"                    , isOperator: true, canAppearAfterOperatorKeyword: true, isBinaryOperator:  true, presedence: 11   , evaledLeftToRight: true, isInFixOperator:   true },
    { representation: "bitand"               , name: "bitwise-and-word"               , isOperator: true,                                      isBinaryOperator:  true, presedence: 11   , evaledLeftToRight: true, isInFixOperator:   true , isOperatorAlias: true},
    { representation: "^"                    , name: "bitwise-xor"                    , isOperator: true, canAppearAfterOperatorKeyword: true, isBinaryOperator:  true, presedence: 12   , evaledLeftToRight: true, isInFixOperator:   true },
    { representation: "xor"                  , name: "bitwise-xor-word"               , isOperator: true,                                      isBinaryOperator:  true, presedence: 12   , evaledLeftToRight: true, isInFixOperator:   true , isOperatorAlias: true},
    { representation: "|"                    , name: "bitwise-or"                     , isOperator: true, canAppearAfterOperatorKeyword: true, isBinaryOperator:  true, presedence: 13   , evaledLeftToRight: true, isInFixOperator:   true },
    { representation: "bitor"                , name: "bitwise-or-word"                , isOperator: true,                                      isBinaryOperator:  true, presedence: 12   , evaledLeftToRight: true, isInFixOperator:   true , isOperatorAlias: true},
    { representation: "&&"                   , name: "logical-and"                    , isOperator: true, canAppearAfterOperatorKeyword: true, isBinaryOperator:  true, presedence: 14   , evaledLeftToRight: true, isInFixOperator:   true , isLogicicalOperator: true},
    { representation: "and"                  , name: "logical-and-word"               , isOperator: true,                                      isBinaryOperator:  true, presedence: 14   , evaledLeftToRight: true, isInFixOperator:   true , isLogicicalOperator: true, isOperatorAlias: true},
    { representation: "||"                   , name: "logical-or"                     , isOperator: true, canAppearAfterOperatorKeyword: true, isBinaryOperator:  true, presedence: 15   , evaledLeftToRight: true, isInFixOperator:   true , isLogicicalOperator: true},
    { representation: "or"                   , name: "logical-or-word"                , isOperator: true,                                      isBinaryOperator:  true, presedence: 15   , evaledLeftToRight: true, isInFixOperator:   true , isLogicicalOperator: true, isOperatorAlias: true},
    { representation: "?:"                   , name: "ternary-conditional"            , isOperator: true,                                      isTernaryOperator: true, presedence: 16.1 , evaledRightToLeft: true,                         },
    { representation: "throw"                , name: "throw"                          , isOperator: true,                                      isUrnaryOperator:  true, presedence: 16.2 , evaledRightToLeft: true, isPreFixOperator:  true , isControlFlow: true, isExceptionRelated: true},
    { representation: "="                    , name: "direct-assignment"              , isOperator: true, canAppearAfterOperatorKeyword: true, isBinaryOperator:  true, presedence: 16.3 , evaledRightToLeft: true, isInFixOperator:   true , isAssignmentOperator: true },
    { representation: "+="                   , name: "addition-assignment"            , isOperator: true, canAppearAfterOperatorKeyword: true, isBinaryOperator:  true, presedence: 16.4 , evaledRightToLeft: true, isInFixOperator:   true , isAssignmentOperator: true },
    { representation: "-="                   , name: "subtraction-assignment"         , isOperator: true, canAppearAfterOperatorKeyword: true, isBinaryOperator:  true, presedence: 16.4 , evaledRightToLeft: true, isInFixOperator:   true , isAssignmentOperator: true },
    { representation: "*="                   , name: "multiplication-assignment"      , isOperator: true, canAppearAfterOperatorKeyword: true, isBinaryOperator:  true, presedence: 16.5 , evaledRightToLeft: true, isInFixOperator:   true , isAssignmentOperator: true },
    { representation: "/="                   , name: "division-assignment"            , isOperator: true, canAppearAfterOperatorKeyword: true, isBinaryOperator:  true, presedence: 16.5 , evaledRightToLeft: true, isInFixOperator:   true , isAssignmentOperator: true },
    { representation: "%="                   , name: "modulus-assignment"             , isOperator: true, canAppearAfterOperatorKeyword: true, isBinaryOperator:  true, presedence: 16.5 , evaledRightToLeft: true, isInFixOperator:   true , isAssignmentOperator: true },
    { representation: "&="                   , name: "bitwise-and-assignment"         , isOperator: true, canAppearAfterOperatorKeyword: true, isBinaryOperator:  true, presedence: 16.7 , evaledRightToLeft: true, isInFixOperator:   true , isAssignmentOperator: true },
    { representation: "and_eq"               , name: "bitwise-and-assignment-word"    , isOperator: true,                                      isBinaryOperator:  true, presedence: 16.7 , evaledRightToLeft: true, isInFixOperator:   true , isAssignmentOperator: true , isOperatorAlias: true},
    { representation: "^="                   , name: "bitwise-xor-assignment"         , isOperator: true, canAppearAfterOperatorKeyword: true, isBinaryOperator:  true, presedence: 16.7 , evaledRightToLeft: true, isInFixOperator:   true , isAssignmentOperator: true },
    { representation: "xor_eq"               , name: "bitwise-xor-assignment-word"    , isOperator: true,                                      isBinaryOperator:  true, presedence: 16.7 , evaledRightToLeft: true, isInFixOperator:   true , isAssignmentOperator: true , isOperatorAlias: true},
    { representation: "|="                   , name: "bitwise-or-assignment"          , isOperator: true, canAppearAfterOperatorKeyword: true, isBinaryOperator:  true, presedence: 16.7 , evaledRightToLeft: true, isInFixOperator:   true , isAssignmentOperator: true },
    { representation: "or_eq"                , name: "bitwise-or-assignment-word"     , isOperator: true,                                      isBinaryOperator:  true, presedence: 16.7 , evaledRightToLeft: true, isInFixOperator:   true , isAssignmentOperator: true , isOperatorAlias: true},
    { representation: ","                    , name: "comma"                          , isOperator: true, canAppearAfterOperatorKeyword: true, isBinaryOperator:  true, presedence: 16.7 , evaledRightToLeft: true, isInFixOperator:   true },
    # no presedence
    { representation: "alignof"              , name: "alignof"                        , isOperator: true,                                                                                                           isFunctionLike:  true },
    { representation: "alignas"              , name: "alignas"                        , isOperator: true,                                                                                                           isFunctionLike:  true },
    { representation: "typeid"               , name: "typeid"                         , isOperator: true,                                                                                                           isFunctionLike:  true },
    { representation: "noexcept"             , name: "noexcept"                       , isOperator: true },
    { representation: "noexcept"             , name: "noexcept"                       , isOperator: true,  isFunctionLike: true },
    { representation: "static_cast"          , name: "static_cast"                    , isOperator: true , isTypeCastingOperator: true},
    { representation: "dynamic_cast"         , name: "dynamic_cast"                   , isOperator: true , isTypeCastingOperator: true},
    { representation: "const_cast"           , name: "const_cast"                     , isOperator: true , isTypeCastingOperator: true},
    { representation: "reinterpret_cast"     , name: "reinterpret_cast"               , isOperator: true , isTypeCastingOperator: true},
    # control
    { representation: "while"                , name: "while"                          , isControlFlow: true, requiresParentheseBlockImmediately: true, },
    { representation: "for"                  , name: "for"                            , isControlFlow: true, requiresParentheseBlockImmediately: true, },
    { representation: "do"                   , name: "do"                             , isControlFlow: true,                                           },
    { representation: "if"                   , name: "if"                             , isControlFlow: true, requiresParentheseBlockImmediately: true, },
    { representation: "else"                 , name: "else"                           , isControlFlow: true,                                           },
    { representation: "goto"                 , name: "goto"                           , isControlFlow: true,                                           },
    { representation: "switch"               , name: "switch"                         , isControlFlow: true, requiresParentheseBlockImmediately: true, },
    { representation: "try"                  , name: "try"                            , isControlFlow: true,                                           isExceptionRelated: true},
    { representation: "catch"                , name: "catch"                          , isControlFlow: true, requiresParentheseBlockImmediately: true, isExceptionRelated: true},
    { representation: "return"               , name: "return"                         , isControlFlow: true,                                           canAppearBeforeLambdaCapture: true },
    { representation: "break"                , name: "break"                          , isControlFlow: true,                                           },
    { representation: "case"                 , name: "case"                           , isControlFlow: true,                                           },
    { representation: "continue"             , name: "continue"                       , isControlFlow: true,                                           },
    { representation: "default"              , name: "default"                        , isControlFlow: true,                                           },
    { representation: "co_await"             , name: "co_await"                       , isControlFlow: true,                                           },
    { representation: "co_yield"             , name: "co_yield"                       , isControlFlow: true,                                           },
    { representation: "co_return"            , name: "co_return"                      , isControlFlow: true,                                           },
    { representation: "discard"              , name: "discard"                        , isControlFlow: true,                                           },
    # primitive type keywords
    # https://en.cppreference.com/w/cpp/language/types
    { representation: "auto"                 , name: "auto"                           , isPrimitive: true, isType: true},
    { representation: "void"                 , name: "void"                           , isPrimitive: true, isType: true},
    { representation: "char"                 , name: "char"                           , isPrimitive: true, isType: true},
    { representation: "short"                , name: "short"                          , isPrimitive: true, isType: true, isTypeSpecifier: true},
    { representation: "int"                  , name: "int"                            , isPrimitive: true, isType: true},
    { representation: "signed"               , name: "signed"                         , isPrimitive: true, isType: true, isTypeSpecifier: true},
    { representation: "unsigned"             , name: "unsigned"                       , isPrimitive: true, isType: true, isTypeSpecifier: true},
    { representation: "long"                 , name: "long"                           , isPrimitive: true, isType: true, isTypeSpecifier: true},
    { representation: "float"                , name: "float"                          , isPrimitive: true, isType: true},
    { representation: "double"               , name: "double"                         , isPrimitive: true, isType: true},
    { representation: "bool"                 , name: "bool"                           , isPrimitive: true, isType: true},
    { representation: "wchar_t"              , name: "wchar_t"                        , isPrimitive: true, isType: true},
    # other types
    { representation: "u_char"               , name: "u_char"               , isType: true },
    { representation: "u_short"              , name: "u_short"              , isType: true },
    { representation: "u_int"                , name: "u_int"                , isType: true },
    { representation: "u_long"               , name: "u_long"               , isType: true },
    { representation: "ushort"               , name: "ushort"               , isType: true },
    { representation: "uint"                 , name: "uint"                 , isType: true },
    { representation: "u_quad_t"             , name: "u_quad_t"             , isType: true },
    { representation: "quad_t"               , name: "quad_t"               , isType: true },
    { representation: "qaddr_t"              , name: "qaddr_t"              , isType: true },
    { representation: "caddr_t"              , name: "caddr_t"              , isType: true },
    { representation: "daddr_t"              , name: "daddr_t"              , isType: true },
    { representation: "div_t"                , name: "div_t"                , isType: true },
    { representation: "dev_t"                , name: "dev_t"                , isType: true },
    { representation: "fixpt_t"              , name: "fixpt_t"              , isType: true },
    { representation: "blkcnt_t"             , name: "blkcnt_t"             , isType: true },
    { representation: "blksize_t"            , name: "blksize_t"            , isType: true },
    { representation: "gid_t"                , name: "gid_t"                , isType: true },
    { representation: "in_addr_t"            , name: "in_addr_t"            , isType: true },
    { representation: "in_port_t"            , name: "in_port_t"            , isType: true },
    { representation: "ino_t"                , name: "ino_t"                , isType: true },
    { representation: "key_t"                , name: "key_t"                , isType: true },
    { representation: "mode_t"               , name: "mode_t"               , isType: true },
    { representation: "nlink_t"              , name: "nlink_t"              , isType: true },
    { representation: "id_t"                 , name: "id_t"                 , isType: true },
    { representation: "pid_t"                , name: "pid_t"                , isType: true },
    { representation: "off_t"                , name: "off_t"                , isType: true },
    { representation: "segsz_t"              , name: "segsz_t"              , isType: true },
    { representation: "swblk_t"              , name: "swblk_t"              , isType: true },
    { representation: "uid_t"                , name: "uid_t"                , isType: true },
    { representation: "id_t"                 , name: "id_t"                 , isType: true },
    { representation: "clock_t"              , name: "clock_t"              , isType: true },
    { representation: "size_t"               , name: "size_t"               , isType: true },
    { representation: "ssize_t"              , name: "ssize_t"              , isType: true },
    { representation: "time_t"               , name: "time_t"               , isType: true },
    { representation: "useconds_t"           , name: "useconds_t"           , isType: true },
    { representation: "suseconds_t"          , name: "suseconds_t"          , isType: true },
    { representation: "int8_t"               , name: "int8_t"               , isType: true },
    { representation: "int16_t"              , name: "int16_t"              , isType: true },
    { representation: "int32_t"              , name: "int32_t"              , isType: true },
    { representation: "int64_t"              , name: "int64_t"              , isType: true },
    { representation: "uint8_t"              , name: "uint8_t"              , isType: true },
    { representation: "uint16_t"             , name: "uint16_t"             , isType: true },
    { representation: "uint32_t"             , name: "uint32_t"             , isType: true },
    { representation: "uint64_t"             , name: "uint64_t"             , isType: true },
    { representation: "int_least8_t"         , name: "int_least8_t"         , isType: true },
    { representation: "int_least16_t"        , name: "int_least16_t"        , isType: true },
    { representation: "int_least32_t"        , name: "int_least32_t"        , isType: true },
    { representation: "int_least64_t"        , name: "int_least64_t"        , isType: true },
    { representation: "uint_least8_t"        , name: "uint_least8_t"        , isType: true },
    { representation: "uint_least16_t"       , name: "uint_least16_t"       , isType: true },
    { representation: "uint_least32_t"       , name: "uint_least32_t"       , isType: true },
    { representation: "uint_least64_t"       , name: "uint_least64_t"       , isType: true },
    { representation: "int_fast8_t"          , name: "int_fast8_t"          , isType: true },
    { representation: "int_fast16_t"         , name: "int_fast16_t"         , isType: true },
    { representation: "int_fast32_t"         , name: "int_fast32_t"         , isType: true },
    { representation: "int_fast64_t"         , name: "int_fast64_t"         , isType: true },
    { representation: "uint_fast8_t"         , name: "uint_fast8_t"         , isType: true },
    { representation: "uint_fast16_t"        , name: "uint_fast16_t"        , isType: true },
    { representation: "uint_fast32_t"        , name: "uint_fast32_t"        , isType: true },
    { representation: "uint_fast64_t"        , name: "uint_fast64_t"        , isType: true },
    { representation: "intptr_t"             , name: "intptr_t"             , isType: true },
    { representation: "uintptr_t"            , name: "uintptr_t"            , isType: true },
    { representation: "intmax_t"             , name: "intmax_t"             , isType: true },
    { representation: "intmax_t"             , name: "intmax_t"             , isType: true },
    { representation: "uintmax_t"            , name: "uintmax_t"            , isType: true },
    { representation: "uintmax_t"            , name: "uintmax_t"            , isType: true },
    { representation: "uintmax_t"            , name: "uintmax_t"            , isType: true },
    # other hlsl types
    { representation: "half"                 , name: "half"                 , isType: true },
    { representation: "bool1"                , name: "bool1"                , isType: true },
    { representation: "bool2"                , name: "bool2"                , isType: true },
    { representation: "bool3"                , name: "bool3"                , isType: true },
    { representation: "bool4"                , name: "bool4"                , isType: true },
    { representation: "int16_t1"             , name: "int16_t1"             , isType: true },
    { representation: "int16_t2"             , name: "int16_t2"             , isType: true },
    { representation: "int16_t3"             , name: "int16_t3"             , isType: true },
    { representation: "int16_t4"             , name: "int16_t4"             , isType: true },
    { representation: "int32_t1"             , name: "int32_t1"             , isType: true },
    { representation: "int32_t2"             , name: "int32_t2"             , isType: true },
    { representation: "int32_t3"             , name: "int32_t3"             , isType: true },
    { representation: "int32_t4"             , name: "int32_t4"             , isType: true },
    { representation: "int64_t1"             , name: "int64_t1"             , isType: true },
    { representation: "int64_t2"             , name: "int64_t2"             , isType: true },
    { representation: "int64_t3"             , name: "int64_t3"             , isType: true },
    { representation: "int64_t4"             , name: "int64_t4"             , isType: true },
    { representation: "int1"                 , name: "int1"                 , isType: true },
    { representation: "int2"                 , name: "int2"                 , isType: true },
    { representation: "int3"                 , name: "int3"                 , isType: true },
    { representation: "int4"                 , name: "int4"                 , isType: true },
    { representation: "uint16_t1"            , name: "uint16_t1"            , isType: true },
    { representation: "uint16_t2"            , name: "uint16_t2"            , isType: true },
    { representation: "uint16_t3"            , name: "uint16_t3"            , isType: true },
    { representation: "uint16_t4"            , name: "uint16_t4"            , isType: true },
    { representation: "uint32_t1"            , name: "uint32_t1"            , isType: true },
    { representation: "uint32_t2"            , name: "uint32_t2"            , isType: true },
    { representation: "uint32_t3"            , name: "uint32_t3"            , isType: true },
    { representation: "uint32_t4"            , name: "uint32_t4"            , isType: true },
    { representation: "uint64_t1"            , name: "uint64_t1"            , isType: true },
    { representation: "uint64_t2"            , name: "uint64_t2"            , isType: true },
    { representation: "uint64_t3"            , name: "uint64_t3"            , isType: true },
    { representation: "uint64_t4"            , name: "uint64_t4"            , isType: true },
    { representation: "uint1"                , name: "uint1"                , isType: true },
    { representation: "uint2"                , name: "uint2"                , isType: true },
    { representation: "uint3"                , name: "uint3"                , isType: true },
    { representation: "uint4"                , name: "uint4"                , isType: true },
    { representation: "half1"                , name: "half1"                , isType: true },
    { representation: "half2"                , name: "half2"                , isType: true },
    { representation: "half3"                , name: "half3"                , isType: true },
    { representation: "half4"                , name: "half4"                , isType: true },
    { representation: "float1"               , name: "float1"               , isType: true },
    { representation: "float2"               , name: "float2"               , isType: true },
    { representation: "float3"               , name: "float3"               , isType: true },
    { representation: "float4"               , name: "float4"               , isType: true },
    { representation: "double1"              , name: "double1"              , isType: true },
    { representation: "double2"              , name: "double2"              , isType: true },
    { representation: "double3"              , name: "double3"              , isType: true },
    { representation: "double4"              , name: "double4"              , isType: true },
    # bool[n]x[n] types
    { representation: "bool1x1"             , name: "bool1x1"             , isType: true },
    { representation: "bool1x2"             , name: "bool1x2"             , isType: true },
    { representation: "bool1x3"             , name: "bool1x3"             , isType: true },
    { representation: "bool1x4"             , name: "bool1x4"             , isType: true },
    { representation: "bool2x1"             , name: "bool2x1"             , isType: true },
    { representation: "bool2x2"             , name: "bool2x2"             , isType: true },
    { representation: "bool2x3"             , name: "bool2x3"             , isType: true },
    { representation: "bool2x4"             , name: "bool2x4"             , isType: true },
    { representation: "bool3x1"             , name: "bool3x1"             , isType: true },
    { representation: "bool3x2"             , name: "bool3x2"             , isType: true },
    { representation: "bool3x3"             , name: "bool3x3"             , isType: true },
    { representation: "bool3x4"             , name: "bool3x4"             , isType: true },
    { representation: "bool4x1"             , name: "bool4x1"             , isType: true },
    { representation: "bool4x2"             , name: "bool4x2"             , isType: true },
    { representation: "bool4x3"             , name: "bool4x3"             , isType: true },
    { representation: "bool4x4"             , name: "bool4x4"             , isType: true },
    # int16_t[n]x[n] types
    { representation: "int16_t1x1"          , name: "int16_t1x1"          , isType: true },
    { representation: "int16_t1x2"          , name: "int16_t1x2"          , isType: true },
    { representation: "int16_t1x3"          , name: "int16_t1x3"          , isType: true },
    { representation: "int16_t1x4"          , name: "int16_t1x4"          , isType: true },
    { representation: "int16_t2x1"          , name: "int16_t2x1"          , isType: true },
    { representation: "int16_t2x2"          , name: "int16_t2x2"          , isType: true },
    { representation: "int16_t2x3"          , name: "int16_t2x3"          , isType: true },
    { representation: "int16_t2x4"          , name: "int16_t2x4"          , isType: true },
    { representation: "int16_t3x1"          , name: "int16_t3x1"          , isType: true },
    { representation: "int16_t3x2"          , name: "int16_t3x2"          , isType: true },
    { representation: "int16_t3x3"          , name: "int16_t3x3"          , isType: true },
    { representation: "int16_t3x4"          , name: "int16_t3x4"          , isType: true },
    { representation: "int16_t4x1"          , name: "int16_t4x1"          , isType: true },
    { representation: "int16_t4x2"          , name: "int16_t4x2"          , isType: true },
    { representation: "int16_t4x3"          , name: "int16_t4x3"          , isType: true },
    { representation: "int16_t4x4"          , name: "int16_t4x4"          , isType: true },
    # int32_t[n]x[n] types
    { representation: "int32_t1x1"          , name: "int32_t1x1"          , isType: true },
    { representation: "int32_t1x2"          , name: "int32_t1x2"          , isType: true },
    { representation: "int32_t1x3"          , name: "int32_t1x3"          , isType: true },
    { representation: "int32_t1x4"          , name: "int32_t1x4"          , isType: true },
    { representation: "int32_t2x1"          , name: "int32_t2x1"          , isType: true },
    { representation: "int32_t2x2"          , name: "int32_t2x2"          , isType: true },
    { representation: "int32_t2x3"          , name: "int32_t2x3"          , isType: true },
    { representation: "int32_t2x4"          , name: "int32_t2x4"          , isType: true },
    { representation: "int32_t3x1"          , name: "int32_t3x1"          , isType: true },
    { representation: "int32_t3x2"          , name: "int32_t3x2"          , isType: true },
    { representation: "int32_t3x3"          , name: "int32_t3x3"          , isType: true },
    { representation: "int32_t3x4"          , name: "int32_t3x4"          , isType: true },
    { representation: "int32_t4x1"          , name: "int32_t4x1"          , isType: true },
    { representation: "int32_t4x2"          , name: "int32_t4x2"          , isType: true },
    { representation: "int32_t4x3"          , name: "int32_t4x3"          , isType: true },
    { representation: "int32_t4x4"          , name: "int32_t4x4"          , isType: true },
    # int64_t[n]x[n] types
    { representation: "int64_t1x1"          , name: "int64_t1x1"          , isType: true },
    { representation: "int64_t1x2"          , name: "int64_t1x2"          , isType: true },
    { representation: "int64_t1x3"          , name: "int64_t1x3"          , isType: true },
    { representation: "int64_t1x4"          , name: "int64_t1x4"          , isType: true },
    { representation: "int64_t2x1"          , name: "int64_t2x1"          , isType: true },
    { representation: "int64_t2x2"          , name: "int64_t2x2"          , isType: true },
    { representation: "int64_t2x3"          , name: "int64_t2x3"          , isType: true },
    { representation: "int64_t2x4"          , name: "int64_t2x4"          , isType: true },
    { representation: "int64_t3x1"          , name: "int64_t3x1"          , isType: true },
    { representation: "int64_t3x2"          , name: "int64_t3x2"          , isType: true },
    { representation: "int64_t3x3"          , name: "int64_t3x3"          , isType: true },
    { representation: "int64_t3x4"          , name: "int64_t3x4"          , isType: true },
    { representation: "int64_t4x1"          , name: "int64_t4x1"          , isType: true },
    { representation: "int64_t4x2"          , name: "int64_t4x2"          , isType: true },
    { representation: "int64_t4x3"          , name: "int64_t4x3"          , isType: true },
    { representation: "int64_t4x4"          , name: "int64_t4x4"          , isType: true },
    # int[n]x[n] types
    { representation: "int1x1"              , name: "int1x1"              , isType: true },
    { representation: "int1x2"              , name: "int1x2"              , isType: true },
    { representation: "int1x3"              , name: "int1x3"              , isType: true },
    { representation: "int1x4"              , name: "int1x4"              , isType: true },
    { representation: "int2x1"              , name: "int2x1"              , isType: true },
    { representation: "int2x2"              , name: "int2x2"              , isType: true },
    { representation: "int2x3"              , name: "int2x3"              , isType: true },
    { representation: "int2x4"              , name: "int2x4"              , isType: true },
    { representation: "int3x1"              , name: "int3x1"              , isType: true },
    { representation: "int3x2"              , name: "int3x2"              , isType: true },
    { representation: "int3x3"              , name: "int3x3"              , isType: true },
    { representation: "int3x4"              , name: "int3x4"              , isType: true },
    { representation: "int4x1"              , name: "int4x1"              , isType: true },
    { representation: "int4x2"              , name: "int4x2"              , isType: true },
    { representation: "int4x3"              , name: "int4x3"              , isType: true },
    { representation: "int4x4"              , name: "int4x4"              , isType: true },
    # uint16_t[n]x[n] types
    { representation: "uint16_t1x1"         , name: "uint16_t1x1"         , isType: true },
    { representation: "uint16_t1x2"         , name: "uint16_t1x2"         , isType: true },
    { representation: "uint16_t1x3"         , name: "uint16_t1x3"         , isType: true },
    { representation: "uint16_t1x4"         , name: "uint16_t1x4"         , isType: true },
    { representation: "uint16_t2x1"         , name: "uint16_t2x1"         , isType: true },
    { representation: "uint16_t2x2"         , name: "uint16_t2x2"         , isType: true },
    { representation: "uint16_t2x3"         , name: "uint16_t2x3"         , isType: true },
    { representation: "uint16_t2x4"         , name: "uint16_t2x4"         , isType: true },
    { representation: "uint16_t3x1"         , name: "uint16_t3x1"         , isType: true },
    { representation: "uint16_t3x2"         , name: "uint16_t3x2"         , isType: true },
    { representation: "uint16_t3x3"         , name: "uint16_t3x3"         , isType: true },
    { representation: "uint16_t3x4"         , name: "uint16_t3x4"         , isType: true },
    { representation: "uint16_t4x1"         , name: "uint16_t4x1"         , isType: true },
    { representation: "uint16_t4x2"         , name: "uint16_t4x2"         , isType: true },
    { representation: "uint16_t4x3"         , name: "uint16_t4x3"         , isType: true },
    { representation: "uint16_t4x4"         , name: "uint16_t4x4"         , isType: true },
    # uint32_t[n]x[n] types
    { representation: "uint32_t1x1"         , name: "uint32_t1x1"         , isType: true },
    { representation: "uint32_t1x2"         , name: "uint32_t1x2"         , isType: true },
    { representation: "uint32_t1x3"         , name: "uint32_t1x3"         , isType: true },
    { representation: "uint32_t1x4"         , name: "uint32_t1x4"         , isType: true },
    { representation: "uint32_t2x1"         , name: "uint32_t2x1"         , isType: true },
    { representation: "uint32_t2x2"         , name: "uint32_t2x2"         , isType: true },
    { representation: "uint32_t2x3"         , name: "uint32_t2x3"         , isType: true },
    { representation: "uint32_t2x4"         , name: "uint32_t2x4"         , isType: true },
    { representation: "uint32_t3x1"         , name: "uint32_t3x1"         , isType: true },
    { representation: "uint32_t3x2"         , name: "uint32_t3x2"         , isType: true },
    { representation: "uint32_t3x3"         , name: "uint32_t3x3"         , isType: true },
    { representation: "uint32_t3x4"         , name: "uint32_t3x4"         , isType: true },
    { representation: "uint32_t4x1"         , name: "uint32_t4x1"         , isType: true },
    { representation: "uint32_t4x2"         , name: "uint32_t4x2"         , isType: true },
    { representation: "uint32_t4x3"         , name: "uint32_t4x3"         , isType: true },
    { representation: "uint32_t4x4"         , name: "uint32_t4x4"         , isType: true },
    # uint64_t[n]x[n] types
    { representation: "uint64_t1x1"         , name: "uint64_t1x1"         , isType: true },
    { representation: "uint64_t1x2"         , name: "uint64_t1x2"         , isType: true },
    { representation: "uint64_t1x3"         , name: "uint64_t1x3"         , isType: true },
    { representation: "uint64_t1x4"         , name: "uint64_t1x4"         , isType: true },
    { representation: "uint64_t2x1"         , name: "uint64_t2x1"         , isType: true },
    { representation: "uint64_t2x2"         , name: "uint64_t2x2"         , isType: true },
    { representation: "uint64_t2x3"         , name: "uint64_t2x3"         , isType: true },
    { representation: "uint64_t2x4"         , name: "uint64_t2x4"         , isType: true },
    { representation: "uint64_t3x1"         , name: "uint64_t3x1"         , isType: true },
    { representation: "uint64_t3x2"         , name: "uint64_t3x2"         , isType: true },
    { representation: "uint64_t3x3"         , name: "uint64_t3x3"         , isType: true },
    { representation: "uint64_t3x4"         , name: "uint64_t3x4"         , isType: true },
    { representation: "uint64_t4x1"         , name: "uint64_t4x1"         , isType: true },
    { representation: "uint64_t4x2"         , name: "uint64_t4x2"         , isType: true },
    { representation: "uint64_t4x3"         , name: "uint64_t4x3"         , isType: true },
    { representation: "uint64_t4x4"         , name: "uint64_t4x4"         , isType: true },
    # uint[n]x[n] types
    { representation: "uint1x1"             , name: "uint1x1"             , isType: true },
    { representation: "uint1x2"             , name: "uint1x2"             , isType: true },
    { representation: "uint1x3"             , name: "uint1x3"             , isType: true },
    { representation: "uint1x4"             , name: "uint1x4"             , isType: true },
    { representation: "uint2x1"             , name: "uint2x1"             , isType: true },
    { representation: "uint2x2"             , name: "uint2x2"             , isType: true },
    { representation: "uint2x3"             , name: "uint2x3"             , isType: true },
    { representation: "uint2x4"             , name: "uint2x4"             , isType: true },
    { representation: "uint3x1"             , name: "uint3x1"             , isType: true },
    { representation: "uint3x2"             , name: "uint3x2"             , isType: true },
    { representation: "uint3x3"             , name: "uint3x3"             , isType: true },
    { representation: "uint3x4"             , name: "uint3x4"             , isType: true },
    { representation: "uint4x1"             , name: "uint4x1"             , isType: true },
    { representation: "uint4x2"             , name: "uint4x2"             , isType: true },
    { representation: "uint4x3"             , name: "uint4x3"             , isType: true },
    { representation: "uint4x4"             , name: "uint4x4"             , isType: true },
    # half[n]x[n] types
    { representation: "half1x1"             , name: "half1x1"             , isType: true },
    { representation: "half1x2"             , name: "half1x2"             , isType: true },
    { representation: "half1x3"             , name: "half1x3"             , isType: true },
    { representation: "half1x4"             , name: "half1x4"             , isType: true },
    { representation: "half2x1"             , name: "half2x1"             , isType: true },
    { representation: "half2x2"             , name: "half2x2"             , isType: true },
    { representation: "half2x3"             , name: "half2x3"             , isType: true },
    { representation: "half2x4"             , name: "half2x4"             , isType: true },
    { representation: "half3x1"             , name: "half3x1"             , isType: true },
    { representation: "half3x2"             , name: "half3x2"             , isType: true },
    { representation: "half3x3"             , name: "half3x3"             , isType: true },
    { representation: "half3x4"             , name: "half3x4"             , isType: true },
    { representation: "half4x1"             , name: "half4x1"             , isType: true },
    { representation: "half4x2"             , name: "half4x2"             , isType: true },
    { representation: "half4x3"             , name: "half4x3"             , isType: true },
    { representation: "half4x4"             , name: "half4x4"             , isType: true },
    # float[n]x[n] types
    { representation: "float1x1"            , name: "float1x1"            , isType: true },
    { representation: "float1x2"            , name: "float1x2"            , isType: true },
    { representation: "float1x3"            , name: "float1x3"            , isType: true },
    { representation: "float1x4"            , name: "float1x4"            , isType: true },
    { representation: "float2x1"            , name: "float2x1"            , isType: true },
    { representation: "float2x2"            , name: "float2x2"            , isType: true },
    { representation: "float2x3"            , name: "float2x3"            , isType: true },
    { representation: "float2x4"            , name: "float2x4"            , isType: true },
    { representation: "float3x1"            , name: "float3x1"            , isType: true },
    { representation: "float3x2"            , name: "float3x2"            , isType: true },
    { representation: "float3x3"            , name: "float3x3"            , isType: true },
    { representation: "float3x4"            , name: "float3x4"            , isType: true },
    { representation: "float4x1"            , name: "float4x1"            , isType: true },
    { representation: "float4x2"            , name: "float4x2"            , isType: true },
    { representation: "float4x3"            , name: "float4x3"            , isType: true },
    { representation: "float4x4"            , name: "float4x4"            , isType: true },
    # double[n]x[n] types
    { representation: "double1x1"           , name: "double1x1"           , isType: true },
    { representation: "double1x2"           , name: "double1x2"           , isType: true },
    { representation: "double1x3"           , name: "double1x3"           , isType: true },
    { representation: "double1x4"           , name: "double1x4"           , isType: true },
    { representation: "double2x1"           , name: "double2x1"           , isType: true },
    { representation: "double2x2"           , name: "double2x2"           , isType: true },
    { representation: "double2x3"           , name: "double2x3"           , isType: true },
    { representation: "double2x4"           , name: "double2x4"           , isType: true },
    { representation: "double3x1"           , name: "double3x1"           , isType: true },
    { representation: "double3x2"           , name: "double3x2"           , isType: true },
    { representation: "double3x3"           , name: "double3x3"           , isType: true },
    { representation: "double3x4"           , name: "double3x4"           , isType: true },
    { representation: "double4x1"           , name: "double4x1"           , isType: true },
    { representation: "double4x2"           , name: "double4x2"           , isType: true },
    { representation: "double4x3"           , name: "double4x3"           , isType: true },
    { representation: "double4x4"           , name: "double4x4"           , isType: true },
    # HLSL resource types
    { representation: "PointStream"                           , name: "PointStream"                           , isType: true },
    { representation: "LineStream"                            , name: "LineStream"                            , isType: true },
    { representation: "TriangleStream"                        , name: "TriangleStream"                        , isType: true },
    { representation: "ConstantBuffer"                        , name: "ConstantBuffer"                        , isType: true },
    { representation: "Buffer"                                , name: "Buffer"                                , isType: true },
    { representation: "RWBuffer"                              , name: "RWBuffer"                              , isType: true },
    { representation: "ByteAddressBuffer"                     , name: "ByteAddressBuffer"                     , isType: true },
    { representation: "RWByteAddressBuffer"                   , name: "RWByteAddressBuffer"                   , isType: true },
    { representation: "StructuredBuffer"                      , name: "StructuredBuffer"                      , isType: true },
    { representation: "RWStructuredBuffer"                    , name: "RWStructuredBuffer"                    , isType: true },
    { representation: "AppendStructuredBuffer"                , name: "AppendStructuredBuffer"                , isType: true },
    { representation: "ConsumeStructuredBuffer"               , name: "ConsumeStructuredBuffer"               , isType: true },
    { representation: "Texture1D"                             , name: "Texture1D"                             , isType: true },
    { representation: "Texture1DArray"                        , name: "Texture1DArray"                        , isType: true },
    { representation: "Texture2D"                             , name: "Texture2D"                             , isType: true },
    { representation: "Texture2DArray"                        , name: "Texture2DArray"                        , isType: true },
    { representation: "Texture2DMS"                           , name: "Texture2DMS"                           , isType: true },
    { representation: "Texture2DMSArray"                      , name: "Texture2DMSArray"                      , isType: true },
    { representation: "Texture3D"                             , name: "Texture3D"                             , isType: true },
    { representation: "TextureCube"                           , name: "TextureCube"                           , isType: true },
    { representation: "TextureCubeArray"                      , name: "TextureCubeArray"                      , isType: true },
    { representation: "RWTexture1D"                           , name: "RWTexture1D"                           , isType: true },
    { representation: "RWTexture1DArray"                      , name: "RWTexture1DArray"                      , isType: true },
    { representation: "RWTexture2D"                           , name: "RWTexture2D"                           , isType: true },
    { representation: "RWTexture2DArray"                      , name: "RWTexture2DArray"                      , isType: true },
    { representation: "RWTexture2DMS"                         , name: "RWTexture2DMS"                         , isType: true },
    { representation: "RWTexture2DMSArray"                    , name: "RWTexture2DMSArray"                    , isType: true },
    { representation: "RWTexture3D"                           , name: "RWTexture3D"                           , isType: true },
    { representation: "RasterizerOrderedBuffer"               , name: "RasterizerOrderedBuffer"               , isType: true },
    { representation: "RasterizerOrderedByteAddressBuffer"    , name: "RasterizerOrderedByteAddressBuffer"    , isType: true },
    { representation: "RasterizerOrderedStructuredBuffer"     , name: "RasterizerOrderedStructuredBuffer"     , isType: true },
    { representation: "RasterizerOrderedTexture1D"            , name: "RasterizerOrderedTexture1D"            , isType: true },
    { representation: "RasterizerOrderedTexture1DArray"       , name: "RasterizerOrderedTexture1DArray"       , isType: true },
    { representation: "RasterizerOrderedTexture2D"            , name: "RasterizerOrderedTexture2D"            , isType: true },
    { representation: "RasterizerOrderedTexture2DArray"       , name: "RasterizerOrderedTexture2DArray"       , isType: true },
    { representation: "RasterizerOrderedTexture3D"            , name: "RasterizerOrderedTexture3D"            , isType: true },
    { representation: "SamplerState"                          , name: "SamplerState"                          , isType: true },
    { representation: "SamplerComparisonState"                , name: "SamplerComparisonState"                , isType: true },
    { representation: "FeedbackTexture2D"                     , name: "FeedbackTexture2D"                     , isType: true },
    { representation: "FeedbackTexture2DArray"                , name: "FeedbackTexture2DArray"                , isType: true },
    { representation: "RaytracingAccelerationStructure"       , name: "RaytracingAccelerationStructure"       , isType: true },
    { representation: "BuiltInTriangleIntersectionAttributes" , name: "BuiltInTriangleIntersectionAttributes" , isType: true },
    { representation: "RayDesc"                               , name: "RayDesc"                               , isType: true },
    { representation: "RayQuery"                              , name: "RayQuery"                              , isType: true },
    { representation: "HitObject"                             , name: "HitObject"                             , isType: true },
    { representation: "EmptyNodeInput"                        , name: "EmptyNodeInput"                        , isType: true },
    { representation: "DispatchNodeInputRecord"               , name: "DispatchNodeInputRecord"               , isType: true },
    { representation: "RWDispatchNodeInputRecord"             , name: "RWDispatchNodeInputRecord"             , isType: true },
    { representation: "GroupNodeInputRecords"                 , name: "GroupNodeInputRecords"                 , isType: true },
    { representation: "RWGroupNodeInputRecords"               , name: "RWGroupNodeInputRecords"               , isType: true },
    { representation: "ThreadNodeInputRecord"                 , name: "ThreadNodeInputRecord"                 , isType: true },
    { representation: "RWThreadNodeInputRecord"               , name: "RWThreadNodeInputRecord"               , isType: true },
    { representation: "NodeOutput"                            , name: "NodeOutput"                            , isType: true },
    { representation: "EmptyNodeOutput"                       , name: "EmptyNodeOutput"                       , isType: true },
    { representation: "NodeOutputArray"                       , name: "NodeOutputArray"                       , isType: true },
    { representation: "EmptyNodeOutputArray"                  , name: "EmptyNodeOutputArray"                  , isType: true },
    { representation: "ThreadNodeOutputRecords"               , name: "ThreadNodeOutputRecords"               , isType: true },
    { representation: "GroupNodeOutputRecords"                , name: "GroupNodeOutputRecords"                , isType: true },
    # literals
    { representation: "NULL"                 , name: "NULL"             , isLiteral: true },
    { representation: "true"                 , name: "true"             , isLiteral: true },
    { representation: "false"                , name: "false"            , isLiteral: true },
    { representation: "nullptr"              , name: "nullptr"          , isLiteral: true },
    # type creators
    { representation: "class"                , name: "class"           , isTypeCreator: true},
    { representation: "struct"               , name: "struct"          , isTypeCreator: true},
    { representation: "union"                , name: "union"           , isTypeCreator: true},
    { representation: "enum"                 , name: "enum"            , isTypeCreator: true},
    # storage specifiers https://en.cppreference.com/w/cpp/language/declarations 
    { representation: "const"                , name: "const"            , isSpecifier: true, isStorageSpecifier: true },
    { representation: "static"               , name: "static"           , isSpecifier: true, isStorageSpecifier: true },
    { representation: "thread_local"         , name: "thread_local"     , isSpecifier: true, isStorageSpecifier: true },
    { representation: "volatile"             , name: "volatile"         , isSpecifier: true, isStorageSpecifier: true },
    { representation: "register"             , name: "register"         , isSpecifier: true, isStorageSpecifier: true },
    { representation: "restrict"             , name: "restrict"         , isSpecifier: true, isStorageSpecifier: true },
    { representation: "extern"               , name: "extern"           , isSpecifier: true, isStorageSpecifier: true, isClassSpecifier: true },
    # HLSL storage specifiers
    { representation: "cbuffer"              , name: "cbuffer"          , isSpecifier: true, isStorageSpecifier: true },
    { representation: "tbuffer"              , name: "tbuffer"          , isSpecifier: true, isStorageSpecifier: true },
    { representation: "linear"               , name: "linear"           , isSpecifier: true, isStorageSpecifier: true },
    { representation: "centroid"             , name: "centroid"         , isSpecifier: true, isStorageSpecifier: true },
    { representation: "nointerpolation"      , name: "nointerpolation"  , isSpecifier: true, isStorageSpecifier: true },
    { representation: "noperspective"        , name: "noperspective"    , isSpecifier: true, isStorageSpecifier: true },
    { representation: "column_major"         , name: "column_major"     , isSpecifier: true, isStorageSpecifier: true },
    { representation: "row_major"            , name: "row_major"        , isSpecifier: true, isStorageSpecifier: true },
    { representation: "in"                   , name: "in"               , isSpecifier: true, isStorageSpecifier: true },
    { representation: "out"                  , name: "out"              , isSpecifier: true, isStorageSpecifier: true },
    { representation: "inout"                , name: "inout"            , isSpecifier: true, isStorageSpecifier: true },
    { representation: "uniform"              , name: "uniform"          , isSpecifier: true, isStorageSpecifier: true },
    { representation: "precise"              , name: "precise"          , isSpecifier: true, isStorageSpecifier: true },
    { representation: "center"               , name: "center"           , isSpecifier: true, isStorageSpecifier: true },
    { representation: "shared"               , name: "shared"           , isSpecifier: true, isStorageSpecifier: true },
    { representation: "groupshared"          , name: "groupshared"      , isSpecifier: true, isStorageSpecifier: true },
    { representation: "snorm"                , name: "snorm"            , isSpecifier: true, isStorageSpecifier: true },
    { representation: "unorm"                , name: "unorm"            , isSpecifier: true, isStorageSpecifier: true },
    { representation: "point"                , name: "point"            , isSpecifier: true, isStorageSpecifier: true },
    { representation: "line"                 , name: "line"             , isSpecifier: true, isStorageSpecifier: true },
    { representation: "lineadj"              , name: "lineadj"          , isSpecifier: true, isStorageSpecifier: true },
    { representation: "triangle"             , name: "triangle"         , isSpecifier: true, isStorageSpecifier: true },
    { representation: "triangleadj"          , name: "triangleadj"      , isSpecifier: true, isStorageSpecifier: true },
    { representation: "globallycoherent"     , name: "globallycoherent" , isSpecifier: true, isStorageSpecifier: true },
    { representation: "reordercoherent"      , name: "reordercoherent"  , isSpecifier: true, isStorageSpecifier: true },
    { representation: "indices"              , name: "indices"          , isSpecifier: true, isStorageSpecifier: true },
    { representation: "vertices"             , name: "vertices"         , isSpecifier: true, isStorageSpecifier: true },
    { representation: "primitives"           , name: "primitives"       , isSpecifier: true, isStorageSpecifier: true },
    { representation: "payload"              , name: "payload"          , isSpecifier: true, isStorageSpecifier: true },
    # function specifiers/qualifiers
    { representation: "inline"               , name: "inline"           , isSpecifier: true , isFunctionSpecifier: true},
    { representation: "constexpr"            , name: "constexpr"        , isSpecifier: true , isFunctionSpecifier: true},
    { representation: "consteval"            , name: "consteval"        , isSpecifier: true , isFunctionSpecifier: true},
    { representation: "mutable"              , name: "mutable"          , isSpecifier: true , isFunctionSpecifier: true},
    { representation: "friend"               , name: "friend"           , isSpecifier: true , isFunctionSpecifier: true},
    { representation: "explicit"             , name: "explicit"         , isSpecifier: true , isFunctionSpecifier: true},
    { representation: "virtual"              , name: "virtual"          , isSpecifier: true , isFunctionSpecifier: true, isInheritanceSpecifier: true },
    { representation: "final"                , name: "final"            , functionQualifier: true, canAppearAfterParametersBeforeBody: true , isValidFunctionName: true, isClassInheritenceSpecifier: true},
    { representation: "override"             , name: "override"         , functionQualifier: true, canAppearAfterParametersBeforeBody: true , isValidFunctionName: true, isClassInheritenceSpecifier: true},
    { representation: "volatile"             , name: "volatile"         , functionQualifier: true, canAppearAfterParametersBeforeBody: true },
    { representation: "const"                , name: "const"            , functionQualifier: true, canAppearAfterParametersBeforeBody: true },
    { representation: "noexcept"             , name: "noexcept"         , isSpecifier: true ,      canAppearAfterParametersBeforeBody: true },
    # if statement specifiers see https://en.cppreference.com/w/cpp/language/if
    { representation: "constexpr"            , name: "constexpr"        , isSpecifier: true , isIfStatementSpecifier: true },
    # lambda specifiers
    { representation: "mutable"                , name: "mutable"            , isLambdaSpecifier: true },
    { representation: "constexpr"              , name: "constexpr"          , isLambdaSpecifier: true },
    { representation: "consteval"              , name: "consteval"          , isLambdaSpecifier: true },
    # accessor
    { representation: "private"               , name: "private"             , isAccessSpecifier: true, isInheritanceSpecifier: true },
    { representation: "protected"             , name: "protected"           , isAccessSpecifier: true, isInheritanceSpecifier: true },
    { representation: "public"                , name: "public"              , isAccessSpecifier: true, isInheritanceSpecifier: true },
    # pre processor directives
    { representation: "if"                    , name: "if"                     , isPreprocessorDirective: true },
    { representation: "elif"                  , name: "elif"                   , isPreprocessorDirective: true },
    { representation: "else"                  , name: "else"                   , isPreprocessorDirective: true },
    { representation: "endif"                 , name: "endif"                  , isPreprocessorDirective: true },
    { representation: "ifdef"                 , name: "ifdef"                  , isPreprocessorDirective: true },
    { representation: "ifndef"                , name: "ifndef"                 , isPreprocessorDirective: true },
    { representation: "define"                , name: "define"                 , isPreprocessorDirective: true },
    { representation: "undef"                 , name: "undef"                  , isPreprocessorDirective: true },
    { representation: "include"               , name: "include"                , isPreprocessorDirective: true },
    { representation: "line"                  , name: "line"                   , isPreprocessorDirective: true },
    { representation: "error"                 , name: "error"                  , isPreprocessorDirective: true },
    { representation: "warning"               , name: "warning"                , isPreprocessorDirective: true },
    { representation: "pragma"                , name: "pragma"                 , isPreprocessorDirective: true },
    { representation: "_Pragma"               , name: "pragma"                 , isPreprocessorDirective: true },
    { representation: "defined"               , name: "defined"                , isPreprocessorDirective: true },
    { representation: "__has_include"         , name: "__has_include"          , isPreprocessorDirective: true },
    { representation: "__has_cpp_attribute"   , name: "__has_cpp_attribute"    , isPreprocessorDirective: true },

    # 
    # misc
    # 
    # https://en.cppreference.com/w/cpp/keyword
    { representation: "this"            , name: "this"          },
    { representation: "template"        , name: "template"      },
    { representation: "namespace"       , name: "namespace"     },
    { representation: "using"           , name: "using"         },
    { representation: "operator"        , name: "operator"      },
    # 
    { representation: "typedef"         , name: "typedef"       , isCurrentlyAMiscKeyword: true },
    { representation: "decltype"        , name: "decltype"      , isSpecifier: true,  isFunctionLike: true },
    { representation: "constinit"       , name: "constinit"     , isSpecifier: true , isCurrentlyAMiscKeyword: true},
    { representation: "typename"        , name: "typename"      },
    # 
    { representation: "asm"                        , name: "asm"                        },
    { representation: "__asm__"                    , name: "__asm__"                    },
    # 
    { representation: "concept"                    , name: "concept"                    , isCurrentlyAMiscKeyword: true },
    { representation: "requires"                   , name: "requires"                   , canAppearAfterParametersBeforeBody: true, isFunctionLike: true },       
    { representation: "export"                     , name: "export"                     , isCurrentlyAMiscKeyword: true },
    { representation: "atomic_cancel"              , name: "atomic_cancel"              },
    { representation: "atomic_commit"              , name: "atomic_commit"              },
    { representation: "atomic_noexcept"            , name: "atomic_noexcept"            },
    { representation: "co_await"                   , name: "co_await"                   },
    { representation: "co_return"                  , name: "co_return"                  },
    { representation: "co_yield"                   , name: "co_yield"                   },
    { representation: "import"                     , name: "import"                     },
    { representation: "module"                     , name: "module"                     , isCurrentlyAMiscKeyword: true },
    { representation: "reflexpr"                   , name: "reflexpr"                   },
    { representation: "synchronized"               , name: "synchronized"               },
    # 
    { representation: "audit"                      , name: "audit"                      , isSpecialIdentifier: true , isValidFunctionName: true},
    { representation: "axiom"                      , name: "axiom"                      , isSpecialIdentifier: true , isValidFunctionName: true},
    { representation: "transaction_safe"           , name: "transaction_safe"           , isSpecialIdentifier: true , isValidFunctionName: true},
    { representation: "transaction_safe_dynamic"   , name: "transaction_safe_dynamic"   , isSpecialIdentifier: true , isValidFunctionName: true},
]



@cpp_tokens = TokenHelper.new tokens, for_each_token: ->(each) do 
    # isSymbol, isWordish
    if each[:representation] =~ /[a-zA-Z0-9_]/
        each[:isWordish] = true
    else
        each[:isSymbol] = true
    end
    # isWord
    if each[:representation] =~ /\A[a-zA-Z_][a-zA-Z0-9_]*\z/
        each[:isWord] = true
    end
    # isBitwise
    if each[:name] =~ /\bbitwise\b/
        each[:isBitwise] = true
    end
    
    if each[:isTypeSpecifier] or each[:isStorageSpecifier]
        each[:isPossibleStorageSpecifier] = true
    end
end



@cpp_support_tokens = TokenHelper.new [
    # io stream
    { representation: "cin"                        , name: "cin"                        , belongsToIostream: true , isVariable: true},
    { representation: "wcin"                       , name: "wcin"                       , belongsToIostream: true , isVariable: true},
    { representation: "cout"                       , name: "cout"                       , belongsToIostream: true , isVariable: true},
    { representation: "wcout"                      , name: "wcout"                      , belongsToIostream: true , isVariable: true},
    { representation: "cerr"                       , name: "cerr"                       , belongsToIostream: true , isVariable: true},
    { representation: "wcerr"                      , name: "wcerr"                      , belongsToIostream: true , isVariable: true},
    { representation: "clog"                       , name: "clog"                       , belongsToIostream: true , isVariable: true},
    { representation: "wclog"                      , name: "wclog"                      , belongsToIostream: true , isVariable: true},
    # stdio
    { representation: "stderr"                     , name: "stderr"                     , belongsToStdio: true , isVariable: true},
    { representation: "stdin"                      , name: "stdin"                      , belongsToStdio: true , isVariable: true},
    { representation: "stdout"                     , name: "stdout"                     , belongsToStdio: true , isVariable: true},
    { representation: "FILE"                       , name: "FILE"                       , belongsToStdio: true , isType: true},
    { representation: "fpos_t"                     , name: "fpos_t"                     , belongsToStdio: true , isType: true},
    { representation: "size_t"                     , name: "size_t"                     , belongsToStdio: true , isType: true},

    # pthread types
    # TODO: I'm not sure if pthread is actually a support type or if it is part of the language spec, I'd assume support
    { representation: "pthread_t"            , name: "pthread_t"            , isType: true , isPthreadType: true },
    { representation: "pthread_attr_t"       , name: "pthread_attr_t"       , isType: true , isPthreadType: true },
    { representation: "pthread_cond_t"       , name: "pthread_cond_t"       , isType: true , isPthreadType: true },
    { representation: "pthread_condattr_t"   , name: "pthread_condattr_t"   , isType: true , isPthreadType: true },
    { representation: "pthread_mutex_t"      , name: "pthread_mutex_t"      , isType: true , isPthreadType: true },
    { representation: "pthread_mutexattr_t"  , name: "pthread_mutexattr_t"  , isType: true , isPthreadType: true },
    { representation: "pthread_once_t"       , name: "pthread_once_t"       , isType: true , isPthreadType: true },
    { representation: "pthread_rwlock_t"     , name: "pthread_rwlock_t"     , isType: true , isPthreadType: true },
    { representation: "pthread_rwlockattr_t" , name: "pthread_rwlockattr_t" , isType: true , isPthreadType: true },
    { representation: "pthread_key_t"        , name: "pthread_key_t"        , isType: true , isPthreadType: true },
]
